### ISSUE TITLE
Error: julia sysimage not set.

### ISSUE THREAD

**Issue by guillametlucia** [sbi-benchmark/diffeqtorch#5]
Hello, 

I followed the instructions to import the diffeqtorch package and I keep getting an error about the sysimage. Do you know how I could solve this? THanks

PS: I am using julia 1.1.0

Python 3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import diffeqtorch
/project/ug/guestug5/Documents/diffeqtorch/diffeqtorch/diffeqtorch.py:29: UserWarning: JULIA_SYSIMAGE_DIFFEQTORCH not set
  warn("JULIA_SYSIMAGE_DIFFEQTORCH not set")
>>>

**Comment by guillametlucia** [comment]
To follow up on that, what about this Julia package made you choose it over integrating the ODEs in Python? Was it just the speed? IF the issue is not resolved do you think I could just do it in Python?

Many thanks.

**Comment by jan-matthis** [comment]
`diffeqtorch` currently requires Julia ≤1.5 due to an upstream issue, see https://github.com/sbi-benchmark/diffeqtorch/issues/3.

This package is using Julia for its autodiff support and speed. Depending on your application, using Python might be fine as well.
